otube/otube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from products.views import index
from products.views import ProductViewSet

from rest_framework import routers

router = routers.SimpleRouter()
router.register(r'product', ProductViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('api/v2/', include(router.urls)),
    path('api/v2/drf-auth/', include('rest_framework.urls'))
    # path('api/v1/productlist/', ProductViewSet.as_view({'get': 'list'})),
    # path('api/v1/productlist/<int:pk>/', ProductViewSet.as_view({'put': 'update'})),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

otube/products/urls.py
from django.urls import path

from products.views import index, add_to_library, delete_library, create

app_name = 'products'

urlpatterns = [
   path('', index, name='products'),
   path('category/<int:category_id>/', index, name='category'),
   path('libraries/add/<int:product_id>/', add_to_library, name='add_to_library'),
   path('libraries/delete/<int:library_id>/', delete_library, name='delete_library'),
   path('create', create, name='create')
]

otube/users/urls.py
from django.urls import path

from users.views import login, registration, profile, logout

app_name = 'users'

urlpatterns = [
   path('login/', login, name='login'),
   path('registration/', registration, name='registration'),
   path('profile/', profile, name='profile'),
   path('logout/', logout, name='logout'),
]

otube/products/models.py
from django.db import models
from users.models import User


class Product(models.Model):
    title = models.CharField(max_length=128)
    description = models.TextField()
    preview = models.ImageField(upload_to='products_images')
    video = models.FileField(upload_to='products_videos')
    category = models.ForeignKey('ProductCategory', on_delete=models.PROTECT)
    user = models.ForeignKey(User, verbose_name='User', on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class ProductCategory(models.Model):
    title = models.CharField(max_length=32)

    def __str__(self):
        return self.title


class Library(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    title = models.CharField(max_length=128)
    description = models.TextField()
    image = models.ImageField(upload_to='products_images')
    video_url = models.URLField()
    created_timestamp = models.DateTimeField(auto_now_add=True)

    
    def __str__(self):
        return f'library for {self.user.username} | Product: {self.product.title}'

otube/products/forms.py
from django import forms
from products.models import Product, ProductCategory


# class UserCreatingLesson(forms.ModelForm):
#     class Meta:
#         model = Product
#         fields = ('title', 'description', 'preview', 'video', 'category')


class UserCreationLesson(forms.ModelForm):
    # title = forms.CharField(widget=(forms.TextInput(attrs={'placeholder': 'title'})))
    # description = forms.CharField(widget=(forms.Textarea(attrs={'cols': '30', 'row': '10'})))
    # preview = forms.ImageField(widget=(forms.FileInput(attrs={'placeholder': 'image'})))
    # video = forms.FileField(widget=(forms.FileInput(attrs={'placeholder': 'video'})))
    # category = forms.ModelChoiceField(queryset=ProductCategory.objects.all())
    
    class Meta:
        model = Product
        fields = ('title', 'description', 'preview', 'video', 'category')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'user-input'}),
            'description': forms.Textarea(attrs={'class': 'user-input', 'cols': '30', 'row': '10'}),
            'preview': forms.FileInput(attrs={'class': 'user-input'}),
            'video': forms.FileInput(attrs={'class': 'user-input'})
        }

otube/products/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from products.models import Product, ProductCategory, Library
from users.models import User
from products.forms import UserCreationLesson
from django.urls import reverse
from rest_framework import generics, viewsets
from rest_framework.decorators import action
from rest_framework.response import Response
from products.serializers import ProductSerializer


class ProductViewSet(viewsets.ModelViewSet):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer


    @action(methods=['get'], detail=False)
    def category(self, request):
        cats = ProductCategory.objects.all()
        return Response({'categories': [cat.title for cat in cats]})


def index(request, category_id=None):
    if category_id:
        products = Product.objects.filter(category_id=category_id)
    else:
        products = Product.objects.all()

    context = {
        'title': 'OTubeProject',
        'products': products,
        'categories': ProductCategory.objects.all()
        }
    return render(request, 'products/index.html', context)


def create(request):
    if request.method == 'POST':
        form = UserCreationLesson(data=request.POST, files=request.FILES)
        if form.is_valid():
            try:
                form.save()
                return HttpResponseRedirect(reverse('index'))
            except:
                print(None, 'ERROR')
            finally:
                print('Work with form done')
    else:
        form = UserCreationLesson()


    context = {
        'title': 'Create Lesson',
        'form': form
    }

    return render(request, 'products/create.html', context=context)


@login_required
def add_to_library(request, product_id):
    product = Product.objects.get(id=product_id)
    libraries = Library.objects.filter(user=request.user, product=product)

    if not libraries.exists():
        Library.objects.create(user=request.user, product=product)
    else:
        print('Already in library')

    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@login_required
def delete_library(request, library_id):
    library = Library.objects.get(id=library_id)
    library.delete()

    return HttpResponseRedirect(request.META['HTTP_REFERER'])

otube/products/templates/products/create.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'hacker/css/index.css' %}">
    <link rel="stylesheet" href="{% static 'hacker/css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'hacker/css/create.css' %}">
</head>
<body>
    <header>
        <div class="header">
            <div class="logo"> {{ title }} </div>
            <div class="search-box">
                <input type="text" placeholder="Поиск по сайту">
            </div>
            <div>
                <section>
                    {% if user.is_authenticated %}
                    <a href="{% url 'users:profile' %}" class="user-button">Profile</a>
                    <a href="{% url 'products:products' %}" class="user-button">Main</a>
                    <a href="{% url 'users:logout'%}" class="user-button">Logout</a>
                    {% if user.is_superuser or user.is_staff %}
                        <a href="{% url 'admin:index' %}" class="user-button">Admin</a>
                    {% endif %}
                    {% else %}
                        <a href="{% url 'users:login' %}" class="user-button">Sign in</a>
                    {% endif %}
                </section>
            </div>
        </div>
    </header>
    <main>
        <section class="form">
            <form action="{% url 'products:create' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <label for="{{ form.title.id_for_label }}">Title</label>
                {{ form.title }}
                
                <label for="{{ form.description.id_for_label }}">Description</label>
                {{ form.description }}
                
                <label for="{{ form.preview.id_for_preview }}">Image</label>
                {{ form.preview }}
                
                <label for="{{ form.video.id_for_label }}">Video</label>
                {{ form.video }}
                <p>
                    <label for="{{ form.category.id_for_category }}">Category</label>
                    {{ form.category }}
                </p>
                <button class="user-save" placeholder="save">Save</button>
            </form>
        </section>
    </main>
    <footer>
        <section class="footer">
            <a href="https://t.me/BountY_Con">Telegram</a>
        </section>
    </footer>
</body>
</html>

otube/products/templates/products/index.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Main</title>
        <link rel="stylesheet" href="{% static 'hacker/css/reset.css' %}">
        <link rel="stylesheet" href="{% static 'hacker/css/index.css' %}">
    </head>
    <body>
        <header>
            <div class="header">
                <div class="logo">{{ title }}</div>
                <div class="search-box">
                    <input type="text" placeholder="Поиск по сайту">
                </div>
                <div>
                    <section>
                        {% if user.is_authenticated %}
                            <a href="{% url 'users:profile' %}" class="user-button">Profile</a>
                            <a href="{% url "products:create" %}" class="user-button">Create lesson</a>
                            <a href="{% url 'users:logout'%}" class="user-button">Logout</a>
                            {% if user.is_superuser or user.is_staff %}
                                <a href="{% url 'admin:index' %}" class="user-button">Admin</a>
                            {% endif %}
                        {% else %}
                            <a href="{% url 'users:login' %}" class="user-button">Sign in</a>
                        {% endif %}
                    </section>
                </div>
            </div>
        </header>
        <main>
            <section class="startup-block-total">
                {% for product in products %}
                    <ul>
                        <li>
                            <div class="startup-block">
                                <h2>
                                    <a class="startup-header" href="#">{{ product.title }}</a>
                                </h2>
                                <video width="400" height="300" controls="control"s poster="{{ product.preview.url }}">
                                    <source src="{{ product.video.url }}" type='video/webm; codecs="vp8, vorbis"'>
                                </video>
                                <p>{{ product.description }}</p>
                                <a class="user-button" href="{% url 'products:add_to_library' product.id %}">Add to library</a>
                            </div>
                        </li>
                    </ul>
                {% endfor %}
            </section>
            <section class="nav-side">
                <div class="site-categories">
                    {% for category in categories %}
                        <ul>
                            <li><a href="{% url "products:category" category.id %}" class="nav-button-categories">{{ category.title }}</a></li>
                        </ul>
                    {% endfor %}
                </div>
            </section>    
        </main>
        <footer>
            <section class="footer">
                something
            </section>
        </footer>    
    </body>
</html>

otube/products/templates/products/libraries.html
{% if libraries %}
    {% for  library in libraries  %}
        <ul>
            <li>
                <div class="user-profile-own-product">
                    <img src="{{ library.product.image.url }}" alt="Image of product" href="{{ library.product.video_url }}">
                    <h3 class="cr-pr-pr" href="{{ library.product.video_url }}"> {{ library.product.title }} </h3>
                    <p> {{ library.user }} </p>
                    <p class="cr-pr-def">{{ library.product.description }}</p>
                    <a class="user-button" href="{% url 'products:delete_library' library.id %}">Delete</a>
                </div>  
            </li>
        </ul>
    {% endfor %}
{% else %}
        <h3 style="color: white; margin-left: 637px; margin-top: 20px;">Have no products</h3>
{% endif %}