otube/otube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from products.views import index
from products.views import ProductViewSet

from rest_framework import routers

router = routers.SimpleRouter()
router.register(r'product', ProductViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('api/v2/', include(router.urls)),
    path('api/v2/drf-auth/', include('rest_framework.urls'))
    # path('api/v1/productlist/', ProductViewSet.as_view({'get': 'list'})),
    # path('api/v1/productlist/<int:pk>/', ProductViewSet.as_view({'put': 'update'})),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

otube/products/urls.py
from django.urls import path

from products.views import index, add_to_library, delete_library, create

app_name = 'products'

urlpatterns = [
   path('', index, name='products'),
   path('category/<int:category_id>/', index, name='category'),
   path('libraries/add/<int:product_id>/', add_to_library, name='add_to_library'),
   path('libraries/delete/<int:library_id>/', delete_library, name='delete_library'),
   path('create', create, name='create')
]

otube/users/urls.py
from django.urls import path

from users.views import login, registration, profile, logout

app_name = 'users'

urlpatterns = [
   path('login/', login, name='login'),
   path('registration/', registration, name='registration'),
   path('profile/', profile, name='profile'),
   path('logout/', logout, name='logout'),
]

otube/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', null=True, blank=True)

otube/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm


from users.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'password'}))

    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'first name'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'last name'}))
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'username'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'placeholder': 'email'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'confirm password'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')


class UserProfileForm(UserChangeForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Mark'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Markov'}))
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Mark', 'readonly': True}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'placeholder': 'umail@gmail.com', 'readonly': True}))
    image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'photo'}), required=False)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'image')

otube/users/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib import auth
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from users.models import User
from users.forms import UserLoginForm, UserRegistrationForm, UserProfileForm
from products.models import Library


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('index'))
    else:
        form = UserLoginForm()

    context = {'form': form}
    return render(request, 'users/login.html', context)


def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            form.messages.success(request, 'Congratulations, your successful registered')
            return HttpResponseRedirect(reverse('users:login'))
    else:
        form = UserRegistrationForm()
    context = {'form': form}
    return render(request, 'users/registration.html', context)


@login_required
def profile(request):
    if request.method == 'POST':
        form = UserProfileForm(instance=request.user, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:profile'))
    else:
        form = UserProfileForm(instance=request.user)

    context = {
        'form': form, 
        'libraries': Library.objects.filter(user=request.user)
    }
    return render(request, 'users/profile.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))

otube/users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sign in</title>
    <link rel="stylesheet" href="/static/hacker/css/reset.css">
    <link rel="stylesheet" href="/static/hacker/css/login.css">
</head>
<body>
    <div class="login-page">
        {% if form.non_field_errors %}
        <div class="errors-handler" style="margin-top: 50px; margin-bottom: 20px; text-align: center; background-color: rgb(194, 194, 132); color: rgb(255, 255, 0); width: 360px; height: 50px; padding: inherit;"> 
            {{ form.non_field_errors }}
        </div>
        {% endif %}
        <div class="form">
            <form class="login-form" action="{% url 'users:login' %}" method="post">
                {% csrf_token %}
                {{ form.username }}
                {{ form.password }}
                <button>login</button>
                <p class="message">Not registered? <a href="{% url 'users:registration' %}">Create an account</a></p>
            </form>
        </div>
      </div>
</body>
</html>

otube/users/templates/users/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile</title>
    <link rel="stylesheet" href="/static/hacker/css/reset.css">
    <link rel="stylesheet" href="/static/hacker/css/index.css">
    <link rel="stylesheet" href="/static/hacker/css/prof.css">
</head>
<body>
    <header>
        <div class="header">
            <a href="{% url 'products:products' %}"><div class="logo">OTubeProject</div></a>
            <div class="search-box">
                <input type="text" placeholder="Поиск по сайту">
            </div>
            <div>
                <section>
                    <a href="{% url "products:create" %}" class="user-button">Create lesson</a>
                    <a href="{% url "products:products" %}" class="user-button">Add lesson</a>
                </section>
            </div>
        </div>
    </header>
    <main>
        <div class="user-profile-change-form">
            <h2 class="header-user">User</h2>
            <div class="photo-profile" style="width: 300px; height: 250px; margin-left: 150px; margin-right: 0px; margin-bottom: 5px;">
                <img src="{% if user.image %} {{ user.image.url }} {% else %} {% static "hacker/images/Blackmonster.jpg" %} {% endif %}" alt="The most sex man in peace">
            </div>
            <form action="{% url 'users:profile' %}" method="post" enctype="multipart/form-data" style="margin-left: 100px; margin-right: 0px;">
                {% csrf_token %}

                <label for="{{ form.first_name.id_for_label }}">Name:</label>
                {{ form.first_name }}

                <label for="{{ form.last_name.id_for_label }}">Surname:</label>
                {{ form.last_name }}

                <label for="{{ form.username.id_for_label }}">Surname:</label>
                {{ form.username }}

                <label for="{{ form.email.id_for_label }}">Mail:</label>
                {{ form.email }}

                {{ form.image }} 
                <label for="{{ form.image.id_for_label }}">Photo:</label>

                <button>Save</button>
            </form>
        </div>
        <h2 class="header-library">Library</h2>
        <div class="list-library">    
            {% include "products/libraries.html" %}
        </div>
    </main>
</body>
</html>

otube/users/templates/users/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sing up</title>
    <link rel="stylesheet" href="/static/hacker/css/reset.css">
    <link rel="stylesheet" href="/static/hacker/css/registration.css">
</head>
<body>
    <div class="login-page">
        {% if form.errors %}
        <div class="errors-handler" style="margin-top: 50px; margin-bottom: 20px; text-align: center; background-color: rgb(194, 194, 132); color: rgb(255, 255, 0); width: 360px;"> 
            {{ form.errors }}
        {% endif %}
        <div class="form">
            <form class="register-form" action="{% url 'users:registration' %}" method="post">
                {% csrf_token %}
                {{ form.first_name }}
                {{ form.last_name }}
                {{ form.username }}
                {{ form.email }}
                {{ form.password1 }}
                {{ form.password2 }}
                <button>create</button>
                <p class="message">Already registered? <a href="{% url 'users:login' %}">Sign In</a></p>
            </form>
        </div>
      </div>
</body>
</html>